### ISSUE TITLE
Question: Could not find git upstream clone which this is relative to (. origin)

### ISSUE THREAD

**Issue by reggi** [joelpurra/gitslave#3]
Hey @joelpurra 

First off thanks so much for your work on this project, I installed the original and ran `gits status` and it failed then upgraded to your version and it worked, very happy about that.

I have a question for you. 

I'd like to create a normal non `--bare` repo and use that as my `superproject` and I'm running into an error where I can't attach a slave to the repo because it's not a clone. I'd appreciate your help. I'm gonna go ahead and put the `--bare` repo within the `repos` folder then clone it but it seems silly. Thoughts?

```
thomas@workstation:project$ git init --shared
Initialized empty shared Git repository in /Users/thomas/Desktop/gitslave-example/project/.git/
thomas@workstation:project$ mkdir -p repos/alpha
thomas@workstation:project$ git -C repos/alpha init --bare --shared
Initialized empty shared Git repository in /Users/thomas/Desktop/gitslave-example/project/repos/alpha/
thomas@workstation:project$ gits prepare
[master (root-commit) 2129f08] gits creating .gitslave
 1 file changed, 0 insertions(+), 0 deletions(-)
 create mode 100644 .gitslave
thomas@workstation:project$ gits attach repos/alpha/ alpha
Could not find git upstream clone which this is relative to (. origin)
```

How can I use `gitslave` without cloning the superproject (not sure what it's called)?

**Comment by joelpurra** [comment]
@reggi: what the error message means is that you don't have any (valid) remote called `origin`. This is true for a newly created (non-cloned) repo. If you add the remote `origin` pointing to the same folder as the superproject (just the dot folder `.`) you can hack it. But this is not what I'd recommend -- it's better to actually have an upstream superproject repo to clone, so you can share the superproject with others (on github, for example).

And to add a note, you should probably keep your `--bare` alpha repo outside of the superproject folder. Here's what I suggest, to get you started.

In the empty folder `my-laboratory`:  

``` bash
mkdir repositories
cd repositories/
git init --bare my-superproject
git init --bare my-alpha
cd ..
mkdir my-superproject
cd my-superproject/
git clone ../repositories/my-superproject/ .
gits prepare
gits attach ../my-alpha/ my-alpha
```

This is the resulting tree structure in `my-laboratory`:  

``` bash
tree -d -L 2
```

``` text
.
├── my-superproject
│   └── my-alpha
└── repositories
    ├── my-alpha
    └── my-superproject

5 directories
```

If this answers your question, please close the issue.

Glad that this `gits` version works for you =)

**Comment by reggi** [comment]
@joelpurra Thank you so much this is amazing. I guess my confusion comes into play when I want each of these repos to have their own github repos, how does that come into play when you have all these `--bare` repos?

**Comment by reggi** [comment]
@joelpurra is there any way to set the default remote for `gitslave` to something other than `origin`?

**Comment by joelpurra** [comment]
@reggi: the bare repos aren't necessary when you already have github repos -- they are already bare repos, only hosted by github.

Here's an example of a github organization I've set up, using gitslave in the meddelare-superproject.
https://github.com/meddelare

Because `git attach` uses relative slave repository addressing (relative to the superproject's `origin`) it's actually easy to move from local development with `--bare` repos to github repos. First you change the `origin` for the superproject to point to `git@github.com:my-laboratory-organization/my-superproject.git`, then you go into each attached subfolder and change their origins to to `git@github.com:my-laboratory/my-alpha.git` and so forth. If you are consistent with your project naming and follow my suggested directory structure above, the repositories are (relatively) addressable from the superproject on github too -- this allows other to do `git clone git@github.com:my-laboratory-organization/my-superproject.git . && gits populate`.

(Turns out this breaks a bit if there's no `master` branch, only a `gh-pages` branch, for example, see meddelare/meddelare-superproject#6.)

**Comment by joelpurra** [comment]
@reggi: should mention that `gits update-remote-url` helps you switch from local to github repositories.

**Comment by joelpurra** [comment]
> @joelpurra is there any way to set the default remote for gitslave to something other than origin?

@reggi: haven't looked in to using a different remote as using `origin` as the base as it's fine with me, but there might be something if looking through the gitslave source code. (A cursory glance doesn't any consistent default base remote selection.)

You could `gits remote add` a remote to all repos, but don't think that's what you're looking for.

**Comment by reggi** [comment]
@joelpurra any idea how to attach a repo that already has been cloned?

Tried both: 

```
thomas@workstation:node-reggi$ gits attach https://github.com/reggi/node-module-bin.git local_modules/module-bin
Destination (local_modules/module-bin) already exists
```

```
thomas@workstation:node-reggi$ gits attach local_modules/module-bin
gits attach requires at least two non-option arguments
Usage: gits attach [--reference=PATH] [--recursive=FILENAME] [--adminonly] REPOSITORY LOCALPATH [FLAGS]
```

**Comment by reggi** [comment]
Also tried just adding this to `.gitslave` I think that `gits attach` does more then just that. Because I can't push.

```
"https://github.com/reggi/node-module-bin.git" "local_modules/module-bin"
```

**Comment by reggi** [comment]
Here's some nonsense that it outputted, can't make heads or tails of it.

``` bash
thomas@workstation:node-reggi$ gits push
Aborting gits push, failed for: 'local_modules/module-bin': exit 128
 (ran fine on:  (node-reggi) local_modules/module-harvest, did not run on 0 other(s); no rollbacks)
  fatal: The current branch master has no upstream branch.
To push the current branch and set the remote as upstream, use

    git push --set-upstream origin master

thomas@workstation:node-reggi$ git push --set-upstream origin master
Branch master set up to track remote branch master from origin.
Everything up-to-date
thomas@workstation:node-reggi$ gits push
Aborting gits push, failed for: 'local_modules/module-bin': exit 128
 (ran fine on:  (node-reggi) local_modules/module-harvest, did not run on 0 other(s); no rollbacks)
  fatal: The current branch master has no upstream branch.
To push the current branch and set the remote as upstream, use

    git push --set-upstream origin master

thomas@workstation:node-reggi$ gits status
# On branch master
On: local_modules/module-bin:
  nothing to commit, working directory clean
On: (node-reggi), local_modules/module-harvest:
  # Your branch is up-to-date with 'origin/master'.
  nothing to commit, working directory clean
thomas@workstation:node-reggi$ gits attach https://github.com/reggi/node-module-bin.git local_modules/module-bin
Destination (local_modules/module-bin) already exists
thomas@workstation:node-reggi$ gits attach local_modules/module-bin
gits attach requires at least two non-option arguments
Usage: gits attach [--reference=PATH] [--recursive=FILENAME] [--adminonly] REPOSITORY LOCALPATH [FLAGS]
thomas@workstation:node-reggi$ 
```

**Comment by reggi** [comment]
If your curious here's my superproject:

https://github.com/reggi/node-reggi

**Comment by reggi** [comment]
[Here's info about my subprojects are getting created](https://github.com/reggi/node-reggi#getting-a-new-module-up-and-running)

**Comment by reggi** [comment]
Then it seems the only way to continue is to remove the new module and clone it again with `gits attach`.

``` bash
$$
thomas@workstation:node-reggi$ rm -rf ./local_modules/module-bin
thomas@workstation:node-reggi$ gits attach https://github.com/reggi/node-module-bin.git local_modules/module-bin
Cloning into 'local_modules/module-bin'...
```

**Comment by reggi** [comment]
Here's even some more context on what I'm trying to achieve.

https://github.com/reggi/node-reggi#gitslave--module-harvest

I'm not happy that I have to remove the dir in order to attach the repo. Seeking alternatives.

**Comment by joelpurra** [comment]
@reggi wrote:

> @joelpurra any idea how to attach a repo that already has been cloned?

Look into `gits attach --reference=PATH`, but you should probably use an already cloned repo that is outside of your superproject.

In general I feel that several of your questions can be answered by reading the manual. You'll get a faster reply from the manual than me, especially when answering multiple questions in a row during the weekend.

**Comment by joelpurra** [comment]
@reggi wrote:

> If your curious here's my superproject:
> https://github.com/reggi/node-reggi

Looks like it'll turn in to quite a collection, and `module-harvest` looks like it can be an interesting automation tool =)

> Then it seems the only way to continue is to remove the new module and clone it again with gits attach.

You might want to look at `gits populate`:

> Go through the list of configured slaves and check out (clone) any which have not already been retrieved.

This might also be a good time to read the gitslave basic tutorial, in case you haven't:
http://gitslave.sourceforge.net/tutorial-basic.html

**Comment by reggi** [comment]
Thanks so much @joelpurra I'm gonna comb over the docs a couple of times really in depth.
