### ISSUE TITLE
Fix pod2man error

### ISSUE THREAD

**Issue by joelpurra** [joelpurra/gitslave#7]
See [bug report+patch on sourceforge](https://sourceforge.net/p/gitslave/bugs/27/) and https://github.com/joelpurra/gitslave/pull/6#issuecomment-246248966.

**Comment by dcwangmit01** [comment]
Pull request here: https://github.com/joelpurra/gitslave/pull/8

**Comment by dcwangmit01** [comment]
Issue closed with merging of pull request
